#!/usr/bin/env bash

WORKSPACE=/home/wanghb/workspace
KLEEDIR=${WORKSPACE}/klee
BUILDDIR=${WORKSPACE}/klee/build
PROG=${BUILDDIR}/bin/klee

function genmake {
  [ -f ${BUILDDIR} ] || mkdir ${BUILDDIR}
  cd ${BUILDDIR}
  cmake -DENABLE_SOLVER_STP=ON -DENABLE_POSIX_RUNTIME=ON -DENABLE_KLEE_UCLIBC=ON -DKLEE_UCLIBC_PATH=${WORKSPACE}/klee-uclibc -DENABLE_UNIT_TESTS=ON -DGTEST_SRC_DIR=${WORKSPACE}/googletest-release-1.7.0 -DLLVM_CONFIG_BINARY=/usr/bin/llvm-config -DLLVMCC=/usr/bin/clang -DLLVMCXX=/usr/bin/clang++ ..
  cd -
}

function build {
  cd ${KLEEDIR}
  cmake --build build
}

function run {
  ${PROG} -cse=bucse -optimize -search=dfs -debug-print-instructions=all:stderr ${WORKSPACE}/examples/$1.bc
}

function runtee {
  ${PROG} -cse=bucse -optimize -search=dfs -debug-print-instructions=all:stderr >/tmp/x 2>&1 ${WORKSPACE}/examples/$1.bc
}

function gencase {
  echo clang -I ${KLEEDIR}/include -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone ${WORKSPACE}/examples/$1.c -o ${WORKSPACE}/examples/$1.bc
  clang -I ${KLEEDIR}/include -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone ${WORKSPACE}/examples/$1.c -o ${WORKSPACE}/examples/$1.bc
}

case "$1" in
  "genmake")
    genmake
    ;;
  "build")
    build
    ;;
  "run")
    run $2
    ;;
  "runtee")
    runtee $2
    ;;
  "gencase")
    gencase $2
    ;;
  *)
    echo "invalid args"
    ;;
esac


